services:
  - type: web
    name: youtube-converter-backend
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
